### ISSUE TITLE
Reskin smart home devices site

### ISSUE THREAD

**Issue by perminder-klair** [perminder-klair/gatsbyjs-ecommerce#25]
On branch https://github.com/perminder-klair/gatsbyjs-ecommerce/tree/site/smart-home-devices

**Comment by perminder-klair** [comment]
For design ideas
https://www.awwwards.com/websites/e-commerce/
https://colorlib.com/wp/template/minishop/
https://colorlib.com/wp/template/sublime/
https://colorlib.com/wp/template/fashiop/
https://colorlib.com/wp/template/theplaza/
https://colorlib.com/wp/template/karma/
https://colorlib.com/wp/template/modist/
https://colorlib.com/wp/template/divisima/
https://colorlib.com/wp/template/aroma/
https://colorlib.com/wp/template/selling/
https://colorlib.com/wp/template/shopmax/

**Comment by gagansaini1212** [comment]
Reskin completed.
