### ISSUE TITLE
Sai feedback - 19 July 2019

### ISSUE THREAD

**Issue by perminder-klair** [perminder-klair/gatsbyjs-ecommerce#54]
- [x] Header - Remove Register button instead add link on register page
- [x] Header - Rename blog to News
- [x] Footer - links to pages leads to same page

- [x] Dashboard - "Find out how now!" need to go to new page named: TV upgrade program
- [x] Dashboard - Hero area - Add SHOP NOW button
- [x] Dashboard - Remove products and show categories instead
- [x] Dashboard - Show latest 10 Featured products
- [x] Dashboard - Remove chat of Sejalsuits

- [ ] Product view - if the product price is 0 (ZERO) then show contact us page instead of add to cart

**Comment by gagansaini1212** [comment]
Footer - links to pages leads to same page
@perminder-klair Can you please check query in --templates --> page.js. The query is not executing if I use edges without array for items.
